spring:
  data:
    mongodb:
      patient:
        database: patient
        uri: mongodb://localhost:27017
      doctor:
        database: doctor
        uri: mongodb://localhost:27017
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration,org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration